#!/bin/bash

BOOST_DIR=/home/nilmini/programs/boost_1_53_0

export BOOSTINC=$BOOST_DIR
export BOOSTLIB=$BOOST_DIR/stage/lib
export LD_LIBRARY_PATH=$BOOST_DIR/stage/lib/

#compile
CXXFLAGS="-c -Wall -std=c++0x -O2 -g -fopenmp"
g++ $CXXFLAGS -I/home/nilmini/programs/boost_1_53_0/ -I../ezpwd-reed-solomon-master/c++/ rs_test.cpp -o rs_test.o
#link
g++ -fopenmp rs_test.o -L/home/nilmini/programs/boost_1_53_0/stage/lib -lboost_program_options -o rs_test.exe
